### ISSUE TITLE
Mismatch mellom avfallstypene i Homey og MinRenovasjon

### ISSUE THREAD

**Issue by runely** [Coderaxx/NorwegianServicesPublic#108]
Homey-appen sier at imorgen hentes bare papir mens MinRenovasjon sier at imorgen hentes papir og matavfall.

Diagnostikkrapport: d381e0f1-4b6e-4b78-a384-7b136f7f9668

![image](https://github.com/Coderaxx/Norske-tjenester/assets/25814673/ffa43bed-bb6e-4d59-b59c-7d552faf8499)

![image](https://github.com/Coderaxx/Norske-tjenester/assets/25814673/00dcc31b-776e-4d86-8d41-029ae9c58a73)

**Comment by runely** [comment]
Dette er fremdeles et problem.

Har sendt en diagnostikkrapport: dbac9064-8989-4d65-9757-637a659dc666

**Comment by Coderaxx** [comment]
Hei!
Jeg fant ikke noe godt svar på hvorfor dette skjer. Det jeg dog har gjort, er å legge inn VESAR som en egen leverandør. For å bruke den nye VESAR leverandøren må du legge til renovasjons-enheten på nytt. Når du skriver inn adressen din, vil du mest sannsynlig få opp at adressen ble funnet hos Min renovasjon. Trykk på "Nei" ved spørsmål om det er riktig leverandør. Du vil da få opp en dropdown-liste med alle leverandører. Her velger du VESAR. Når dette blir valgt, skal du automatisk havne på neste steg, som er "Legg til enheter". Hyl gjerne ut dersom du står fast, eller støter på problemer.😄

**Comment by runely** [comment]
Det hjalp! 👍
