### ISSUE TITLE
Udefinert i Bærum

### ISSUE THREAD

**Issue by HaraldRex** [Coderaxx/NorwegianServicesPublic#17]
Hei,

Får opp at noe (undefined) skal bli hentet om 21 dager i Bærum

![image](https://user-images.githubusercontent.com/75989717/234319857-b90fabb8-36d7-4e6a-8d31-cd697080883e.png)

Papp/Papir og plastavfall er korrekt iht. MinRenovasjon:

![image](https://user-images.githubusercontent.com/75989717/234319598-d6f59504-6239-4a45-bf23-4ff95a39ff48.png)

**Comment by Coderaxx** [comment]
Det er en bug i nedtellingen i den versjonen som ligger ute dessverre. Dette er fikset i neste oppdatering, som straks er klar!☺️

**Comment by HaraldRex** [comment]
Jeg fikk ikke dette til å fungere bedre enn nevnt ovenfor, så jeg prøvd å slette renovasjons enheten og legge den til på nytt.

Nå får jeg bare denne:

![image](https://user-images.githubusercontent.com/75989717/236387586-ad99e4db-401a-4a7f-a747-57d5e529d77f.png)

**Comment by HaraldRex** [comment]
Det problemet forsvant da hele appen ble avinstallert og lagt inn på nytt.

Da var det altså 2 issues: 

1. Oppdatering av appen alene (automatisk) løste ikke det opprinnelige problemet
2. Fjerne device og legge til på nytt gir "flowtoken_already_exists"
