### ISSUE TITLE
Ringsaker Kommune

### ISSUE THREAD

**Issue by Awtomatig** [Coderaxx/NorwegianServicesPublic#2]
Her er min renovasjon fra Ringsaker: ![image](https://user-images.githubusercontent.com/81908056/232743781-ff68fe89-420f-4c12-9a0d-5ab6bcde5866.png)

Takk for Finn app😃

**Comment by Coderaxx** [comment]
Hei! Hmm, dette så ikke helt riktig ut nei. Har du mulighet til å opprette en diagnostikkrapport, og sende meg koden du får opp? I kommentaren når du oppretter rapporten, kan du gjerne skrive adressen det gjelder.
Gå inn på apper-siden på Homey, finn Norske tjenester, velg innstillinger, deretter opprett diagnostrikkrapport. 😄

**Comment by Awtomatig** [comment]
9072eaf1-5c6a-45dc-afe8-226be326c1c7
