### ISSUE TITLE
Feil dato for henting av restavfall (MinRenovasjon)

### ISSUE THREAD

**Issue by edzepp** [Coderaxx/NorwegianServicesPublic#25]
Etter oppdatering til versjon 1.2.4 så har datoer for henting av restavfall blitt feil. Jeg bruker MinRenovasjon (Bærum)

![57C4BFD0-A620-42D7-9DB4-6681DE916975](https://user-images.githubusercontent.com/17829674/236132809-10532cac-28c3-4d06-bc2a-8597991ee7de.jpeg)

**Comment by Coderaxx** [comment]
Hei! Det har kommet noen oppdateringer siden 1.2.4, som forhåpentligvis har fikset feilen. Gi gjerne tilbakemelding dersom det fortsatt ikke fungerer.

**Comment by Coderaxx** [comment]
Her er nok nor på tur ja.. Hvilken versjon av appen kjører du?

**Comment by edzepp** [comment]
Prøvde avinstallasjon nå. Samme feil. 1.2.19

**Comment by Coderaxx** [comment]
Da skal jeg ta en nærmere titt på det. Kunne du gitt meg adressen du får feil på?

**Comment by edzepp** [comment]
Tusen takk for det👍 flott app btw

Du kan f.eks se på denne adressen:
Nyveien 3, 1369 Stabekk, Norg

**Comment by Coderaxx** [comment]
Har tatt en nærmere titt på det, og fikset feilen. Kommer i neste oppdatering!😄
