### ISSUE TITLE
Renovasjon oppdaterer seg ikke

### ISSUE THREAD

**Issue by runely** [Coderaxx/NorwegianServicesPublic#28]
Har installert siste versjon, 1.2.19.

Renovasjon ble vist riktig når devicen ble opprettet, men den har ikke oppdatert seg siden opprettelsen.

![image](https://user-images.githubusercontent.com/25814673/236931067-52d7e554-9937-4409-b74f-9de89758ea78.jpeg)

**Comment by Coderaxx** [comment]
Hei! Dette er fikset i siste versjon av appen, 1.3.2😊 Ruller den ut forhåpentligvis senere i dag

**Comment by runely** [comment]
Hei

Renovasjonsdagene oppdateres fremdeles ikke på **1.3.2**.

Dagene ble oppdatert riktig rett etter oppdatering til **1.3.2**, men de oppdateres ikke videre.

Det nye OG-kortet, `Søppel hentes i morgen` fungerer ikke da den tror at hentedagen er en annen.

![image](https://github.com/Coderaxx/NorwegianServicesPublic/assets/25814673/ac4b68fe-ee86-4258-a2a7-6a9a25a9977c)

![image](https://github.com/Coderaxx/NorwegianServicesPublic/assets/25814673/8095b883-2cc7-4e8a-a61d-8494dc6e6574)

**Comment by runely** [comment]
Renovasjon har ikke oppdatert seg til idag. Så OG-kortet `Søppel hentes idag` fungerer ikke.

Diagnostikkrapport sendt: 647d6d14-0ebb-47d2-965f-8657925ade8b

![image](https://github.com/Coderaxx/NorwegianServicesPublic/assets/25814673/315dd67c-8f7c-4943-b079-d2e3c2864f48)

**Comment by runely** [comment]
Fant du ut noe på diagnostikkrapporten jeg sendte?

Renovasjon har fremdeles ikke oppdatert seg her siden appen ble startet.

Si ifra hvis du trenger en ny diagnostikkrapport

**Comment by runely** [comment]
Funker etter siste oppdatering, 1.3.3
