### ISSUE TITLE
[IDÉ] OG-kort for søppel hentes idag + global tag for søppeltyper

### ISSUE THREAD

**Issue by runely** [Coderaxx/NorwegianServicesPublic#29]
Jeg ønsker meg et OG-kort for om det hentes søppel idag eller ikke. Gjerne med mulighet til å spesifisere hva slags søppeltype.

Jeg ønsker meg også en global tag som inneholder de søppeltypene som hentes ved neste tømming.

Da kan jeg lage en flow som kjøres på morningen når jeg står opp, som kun fullfører dersom det hentes søppel idag (via OG-kort), og som leser opp hvilke søppeltyper som hentes (via global tag) over sonos anlegget 😎

**Comment by Coderaxx** [comment]
Hei! Takk for gode innspill!😄 OG-flow kort, samt global tag med avfallstyper neste henting er allerede implementert i versjon 1.3.1 som ligger tilgjengelig i Homey app store nå😁
Har for øvrig ikke enda implementert OG-kort med spesifikke avfallstyper. Det er planen å implementere, men ser litt på nødvendigheten rundt akkurat dette, når man kan bruke global tag😊
<img width="288" alt="Screenshot_1" src="https://user-images.githubusercontent.com/48462275/237052473-b3414ce7-078e-44f9-b3fb-c3d7b64d5db8.png">
<img width="299" alt="Screenshot_2" src="https://user-images.githubusercontent.com/48462275/237052478-93db4564-5a36-46fe-b6c5-141137601e9e.png">

**Comment by runely** [comment]
Ahh, Nice! 👍
