### ISSUE TITLE
Tynset kommune - plast

### ISSUE THREAD

**Issue by erlendoyen** [Coderaxx/NorwegianServicesPublic#79]
Hei

tidligere fungerte varsel for plastavfall for Tynset kommune, det gjør det ikke lenger.

![image](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/b7ea9765-35b6-40b1-9262-923d0cd3205c)

![image](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/eb1102b4-15d8-40b1-8601-9c8a085a3d00)

**Comment by erlendoyen** [comment]
@Coderaxx hei noe ide om hva som er feil her?

**Comment by Coderaxx** [comment]
Hei!
Tynset skal i utgangspunktet fungere gjennom Min renovasjon, men jeg har nå lagt til støtte for FIAS, dersom Min renovasjon ikke funker på alle adresser i Tynset 😄

**Comment by erlendoyen** [comment]
Genialt, min renovasjon viser riktig

Men ikke i norske tjenester

Det funka fint ganske lenge. 

Mat og plast er alltid på samme dag

Slik ser det ut nå
Det som er rart er at i starten av måneden er dato rett, så litt uti må ende så flytter plast seg i norske tjenester til dagen for papir 

![Screenshot_20231112_092154_MinRenovasjon](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/7d0240fe-c402-4652-8c1b-c281c003b69f)


![Screenshot_20231112_092145_Homey](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/9708c7e4-fc20-49ca-b483-ca7ad1ec7535)

**Comment by erlendoyen** [comment]
Ser også det er feil dato her også for plast

![Screenshot_20231113_221416_Homey](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/3f64b056-783e-47b4-bd8e-c0e0fe787ecb)


Vs


![Screenshot_20231113_221612_MinRenovasjon](https://github.com/Coderaxx/Norske-tjenester/assets/96687238/5669c230-cab3-48ca-a683-d6423a7f9e2a)

**Comment by erlendoyen** [comment]
Hei

Dato for henting av plast blir fortsatt feil.
Det er rett til en gitt dato i måneden, etter dette er det rett i min renovasjon, men feil i norske tjenester enheten.
