### ISSUE TITLE
[Renovasjon] BIR

### ISSUE THREAD

**Issue by Djmurre** [Coderaxx/NorwegianServicesPublic#86]
**Hvilket renovasjonsselskap mangler?**

BIR
**Tilleggsinformasjon**
Hvis du har tilleggsinformasjon, skriv det her. Skriv gjerne adressen din her, slik at det blir enklere å legge inn støtte for ditt renovasjonsselskap.
Etter manglende oppdateringer (begynte 1/11)  fra BIR restartet jeg app, dette løste ikke problem. Prøvde derfor ny enhet, får valgt adresse men, får feilmelding mangler tømme kalender.  Har prøvd to adresse i Bergen med samme feil.

P.s Fantastisk app😀

**Comment by Coderaxx** [comment]
Hei! Takk for at du meldte ifra.😄 BIR skal nå være i orden igjen. 😃
