### ISSUE TITLE
Minus days for renovation

### ISSUE THREAD

**Issue by proisland** [Coderaxx/NorwegianServicesPublic#87]
Suddenly my next pickup for renovation show that its several hundred days in the past.

![IMG_9774](https://github.com/Coderaxx/Norske-tjenester/assets/43773130/33b5fdfa-8c54-4981-8031-0e2d0d2036d1)
![IMG_9773](https://github.com/Coderaxx/Norske-tjenester/assets/43773130/7db95a9a-451e-46b8-9592-4b9cec95fd5c)

**Comment by erlingbo** [comment]
Same happens for me now. Guess it is because one of the pickups is scheduled for January next year and the calculation does not consider year and thus thinking January is on the past.

**Comment by Coderaxx** [comment]
Thanks for your feedback!😄 I have fixed this issue, which was indeed due to a miscalculation of dates, when the response didn't specify the year. If you're still experiencing this issue, please let me know!🙂👍🏼
