### ISSUE TITLE
[Renovasjon] Tilgjengeliggjøre søppeltype tag globalt [IDÉ] 

### ISSUE THREAD

**Issue by EilevHagen** [Coderaxx/NorwegianServicesPublic#88]
**Beskriv idéen din**
Man får tak i den globale taggen "Neste henting" (antall dager til neste henting) i alle flows. Men ikke "Søppeltype", den får man kun tak i via startpunktet "Søppel hentes i morgen". Kan den også tilgjengeliggjøres globalt?

**Beskriv hvilke funksjoner idéen din har**
Jeg kommer til å bruke det i en statusbeskjed som lese opp daglig via en høytaler, som bl.a. skal si hvor mange dager det er til neste søppeltype hentes.

**Comment by Coderaxx** [comment]
Hei! Takk for innspill!😄
Dette skal være tilgjengelig. Får du ikke opp disse?
![image](https://github.com/Coderaxx/Norske-tjenester/assets/48462275/98ae8941-9ab7-4864-9564-9d886094c9a6)

**Comment by EilevHagen** [comment]
Den lå under en annen kategori ja, fant den nå. Takk skal du ha :)
