### ISSUE TITLE
Oppdatering av renovasjonsdager fungerer ikke lenger

### ISSUE THREAD

**Issue by runely** [Coderaxx/NorwegianServicesPublic#95]
Etter en av de siste oppdateringene, usikker på hvilken, så oppdaterer ikke renovasjonsdagene seg lenger i devicen.

Condition kortet `Søppel hentes i dag/morgen` er heller ikke korrekt. I flere dager har den ment at i morgen hentes søppel, og her hentes det bare på fredager.

Har ikke prøvd å fjerne/legge til devicen igjen da jeg har aktive flows på devicen

![image](https://github.com/Coderaxx/Norske-tjenester/assets/25814673/35e9d58a-df5d-4faa-ac23-31c93a4273b3)

**Comment by Coderaxx** [comment]
Kunne du tatt en restart av appen i Homey, så venter du ish 1 min, og deretter oppretter en diagnostikkrapport? Da kan jeg få tatt en titt på hva som skjer😄👍🏼

**Comment by runely** [comment]
Diag opprettet og sendt: ff2b5f3f-56ca-4f2e-8644-ccdaadc95bfd

Ser i avanserte innstillinger at det står Nei på alle avfallsinnstillinger. Har det noe å si? Er det noe nytt? 🤔

![image](https://github.com/Coderaxx/Norske-tjenester/assets/25814673/dc9af2d4-8a1f-4691-9889-ca482d82ad33)

**Comment by runely** [comment]
Satte `Plastavfall` til **Ja** men ingen endring. Selv ikke etter en restart av appen

**Comment by Coderaxx** [comment]
Alle valgene burde stå på "Ja", så lenge du ikke har et type avfall du ikke ønsker å ha i Homey. Jeg får oppdaterte verdier på din adresse. Hvis det fortsatt ikke funker, kan du prøve å legge til enheten på nytt, og se om det hjelper. 😄 
![Screenshot](https://i.gyazo.com/7129af0236bfd4d3913dab0ea496f7d2.png)

**Comment by runely** [comment]
Men hvorfor er alle valgene på `Nei`? 

Jeg har ikke gjort noen endringer siden jeg la til devicen for noen måneder siden

**Comment by runely** [comment]
Er de valgene lagt til i appen etter at jeg la til devicen? Så de har defulted til `Nei` ?

**Comment by runely** [comment]
Har satt alle valgene til `Ja` og restartet appen, men endring endring..

Forøvrig så er det to valg som begge heter `Restavfall` 🤔

![image](https://github.com/Coderaxx/Norske-tjenester/assets/25814673/394fb667-7880-46b5-99a2-d31f83c29b46)

**Comment by runely** [comment]
Fjernet og la til devicen på nytt. Da fungerer det..

Det er flere nye endringer i devicen nå enn tidligere. Blant annet noe om API v 1.0.0, så det er tydelig at ny versjon av appen breaker funksjonalitet for eksisterende devicer.

**Comment by Coderaxx** [comment]
Hei,

Takk for detaljert informasjon og for å ha fulgt trinnene for feilsøking. Det ser ut som problemet du har opplevd, kan være knyttet til introduksjonen av nye funksjoner i enheten som ikke har blitt oppdatert riktig på din side. Dette er spesielt merkbart med de nye innstillingene som var satt til "Nei" – dette er uvanlig, da disse innstillingene vanligvis defaultes til "Ja". Det kan tyde på en feil under oppdateringsprosessen.

Jeg har gjennomført omfattende testing på disse funksjonene, og så langt har ingen andre rapportert om lignende problemer. Det er godt å høre at problemet ble løst ved å fjerne og legge til enheten på nytt, da dette noen ganger kan være nødvendig etter større oppdateringer for å sikre at alle nye funksjoner og endringer blir riktig implementert.

Din tilbakemelding er veldig verdifull, og jeg vil forsikre meg om at fremtidige oppdateringer tester for og håndterer slike tilfeller mer effektivt. Fortsett å dele dine erfaringer, og la meg vite om du støter på noen andre utfordringer!

Ha en fin dag og lykke til videre med bruk av appen! 😄👍🏼
